### PR TITLE
Added sponsors

### PR DESCRIPTION
**Pull request by ronika-das**
I have added sponsors as mentioned in the issue :
  progate
  eckovation
  hackerank
  o'reilly
Letme know any changes

### CODE REVIEW

**Comment by Aniket965** [comment]
hey can you share a screenshot for how its looking in your branch

**Comment by ronika-das** [comment]
ss intel

**Comment by Aniket965** [comment]
great thank you so much ❣️ happy hacktoberfest

**Comment by ronika-das** [comment]
welcome!

**Pull request merged**
